<?php echo $this->doctype() ?>
<html lang="pt_Br">
    <!-- backend auth -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="<?php echo $this->baseUrl; ?>" />
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <noscript>
            <div class="alert alert-warning" role="alert">
                <i class="fa fa-exclamation-triangle"></i> O javascript do seu navegador parece estar desabilitado.
            </div>
        </noscript>
        <div class="container auth">
            <?php echo $this->messages(); ?>
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="display: none">
                            <h2 class="panel-title"><?php echo $this->escape($this->title) ?></h2>
                        </div>
                        <div class="panel-body">
                            <?php echo $this->layout()->content; ?>
                        </div>
                        <div class="panel-footer">
                            <span class="copyright">Desenvolvido por DB9 Tecnologia de Dados</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>