<?php echo $this->doctype() ?>
<!--[if IE 9]><html class="lt-ie10" lang="pt-br" ><![endif]-->
<html class="no-js" lang="pt-br" >
    <!-- Auth -->
    <head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="<?php echo $this->baseUrl; ?>" />
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
    </head> 
    <body>
        <noscript>
        <div class="alert alert-warning" role="alert">
            <i class="fa fa-exclamation-triangle"></i> O javascript do seu navegador parece estar desabilitado.
        </div>
        </noscript>
        <div class="row">
            <div class="large-5 medium-7 medium-centered large-centered columns">
                <?php echo $this->messages(); ?>
            </div>
        </div>
        
        <?php echo $this->layout()->content; ?>

        <?php echo $this->inlineScript(); ?>
    </body> 
</html>