<?php echo $this->doctype() ?>
<!--[if IE 9]><html class="lt-ie10" lang="pt-br" ><![endif]-->
<html class="no-js" lang="pt-br" > 
    <!-- Default -->
    <head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="<?php echo $this->baseUrl; ?>" />
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
    </head> 
    <body> 
        <a id="hamburger" class="FixedTop" href="#menu"><span></span></a>
        <h2><?php echo $this->escape($this->title) ?></h2>
        <?php echo $this->escape($this->description) ?>
        <?php echo $this->messages(); ?>
        <?php echo $this->layout()->content; ?>

        <?php echo $this->navigation(); ?>
        <?php echo $this->inlineScript(); ?>
    </body> 
</html>