<?php echo $this->doctype() ?>
<html lang="pt_Br">
    <!-- backend root -->
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="<?php echo $this->baseUrl; ?>" />
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <div class="container-fluid">
            <a id="hamburger" class="FixedTop" href="#menu"><span></span></a>
            <h2><?php echo $this->escape($this->title) ?></h2>
            <?php echo $this->escape($this->description) ?>
            <?php echo $this->messages(); ?>
            <?php echo $this->layout()->content; ?>
        </div>
        <?php echo $this->navigation(); ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>